apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tt-api
  template:
    metadata:
      labels:
        app: tt-api
    spec:
      containers:
        - name: my-app-container
          image: us-central1-docker.pkg.dev/tourtimegolf/tt-api/tt-api:latest
          env:
            - name: pass
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: secret     # name of secret file
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: super-secret
      restartPolicy: Always            