apiVersion: ENC[AES256_GCM,data:HYI=,iv:pPbvKFEWwQoTTcdkBqSU5NMNbzRg0a7F26JOTi01sL8=,tag:3ph6aBiPM3FU8WWw+8vCIQ==,type:str]
kind: ENC[AES256_GCM,data:h2axFAnl,iv:qlVL2Qn2R/GdwZWrTxfr7sp5S21jV5TgOJdg2Q0+MBA=,tag:02xfF1FkblbJ5muzfGT32g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1EXi4EAbjxy7b+eO,iv:GdYgxa6+OpUl8t0+/gPvaFWHOl5rVQ7SPi7RthPQebk=,tag:t7ZMTw8puXBQChFFkf6Nmg==,type:str]
    #ENC[AES256_GCM,data:eYEQeqaPh77FvrBfcw==,iv:dX9WxYiek81L+vc5k7BqHJKtyOFYKjv1NCGomXB+O1c=,tag:7SBfBrH0LAW2vPdCzgS8hg==,type:comment]
    #ENC[AES256_GCM,data:cF9GWMnUj/ob9TF/SfwCh420ao+33rqbcjePyMbpM2/Ob9zTb5he9dtQAHk=,iv:ErZx/XLvBqk8wgYo26tMoRSygbmqwaBAdXDNqtGlF80=,tag:pDtVpI5ngEjkLAwskJ+RRg==,type:comment]
type: ENC[AES256_GCM,data:9Xy4X9Lh,iv:QHEZ7o9WKSDze5YJGk/HvGzf15hHygOlRDuKSCp+FLU=,tag:8z95FllG2QDX8zBYQWoGHw==,type:str]
data:
    API_KEY: ENC[AES256_GCM,data:YQMjGONcsA9mdC2M7aXKLRUxPZg=,iv:DSj8qVw8FbW16nRhJY8b1wt2y/cHDE0UeNiiHR3LcYo=,tag:Nk32HzRZ1SpDMcouyjwv0g==,type:str]
    DB_PASS: ENC[AES256_GCM,data:FotUh3D3X1gZPzE=,iv:ZoRyHUe2JjN+DHLEcIm6d8BNfOMOMOHUIKNcQUGegZE=,tag:OurEtRXdOUlzAGaRItU8MQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tourtimegolf/locations/us-central1/keyRings/tt-api-dev/cryptoKeys/gke
          created_at: "2024-01-23T19:11:41Z"
          enc: CiQA6t9206E1Bmuf5ZIPLH81K5qDHY8JK6bajNa2KKuqiweywsgSSQBbbne9XCfrNq/2/0CG2X+6mOhOJlz3b++jmGskRicAA6+lloc3b+WY2A9lqan1kTGByWzKArVMeBUecDeiOe6idnIsLGvOr+Q=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T19:11:41Z"
    mac: ENC[AES256_GCM,data:ys3+yPTa1q3F1QVBcF1tPkC9vuk/FLH4B+QJ0onhZTiwMjlG2bn6dz89t2TjMtfXwg1ZrSJxGfOH6EklHcgcIrudWZhq53DZczAfpP1fYTqgPbPsNRIVOQo4DzOYqASXdphWEu0LvAEUqGlFgUb0bPL9ZWX9pdtKLtEwvjUness=,iv:vQIiwQykfqDaoZkC1nirhm1CuOusg1nQUSj7zdmI3+A=,tag:uh77YpU5JMKHUnqEjGv8BQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
