apiVersion: ENC[AES256_GCM,data:F80=,iv:OkFYGjWaKExnnGjd+JvniOneX40yeSFlFD6vb0iFA/A=,tag:FBSD/UNU2tWzuMxTETMvmw==,type:str]
kind: ENC[AES256_GCM,data:IDoLv3+d,iv:M9It6czw25gLIc1mWn8xT4lmOnubwHEqcrABIS2cAhc=,tag:OEbr2FuGrjgt3unGmVaNeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ImODbbKyIQaduQOV,iv:iUR1RYtyF4TouF1ciAsJrbnlex2GeRU/TtklxCbgoxY=,tag:855yKACOD2KG5DFuwuQ7zg==,type:str]
data:
    SUPER_SECRET: ENC[AES256_GCM,data:aIEkh7isCrHtBzrWl8FMai8X9jE=,iv:UlkxbX2a+PntFcYsihAo2DhlrBLEbNEjIupggTQqv0g=,tag:IajeSM8a1Z7J6ROXB/MECg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tourtimegolf/locations/us-central1/keyRings/tt-api-dev/cryptoKeys/gke
          created_at: "2024-01-23T05:37:26Z"
          enc: CiQA6t9207UbGJ6tLlgLx4uIwBNMDYG379K3bGJfhmqdgTRY8ZASSQBbbne9Xw6LYLVcfRSBCYdRx4w1mLVRRdlXlo3oFFgpK4YhUqMyLoTotm9YacjQMunxIZnaZ7jAnmnuJWpOcDc0JQqJG7EFUS0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T05:37:27Z"
    mac: ENC[AES256_GCM,data:PsFJ9qyKyJTEAnAzEMZ65hKZ73V38mZDYsv5T4gc8BIfxtDdxqnM6F9LNHyMG2hYi8oa5hJYnJ4hHUZ1Dli7m6WIwrwGxv0a2kfCUJrHGz21hiclImk1BG7O5uuxr19THF4gY53+hIISJbPorcXZhXK54G9949TG/PPrq2PeWos=,iv:boGpbre5aqa4UF9tN9+azGzUdkN3UcexORd6ccwQEJ0=,tag:/tJju0xMmSg9XbqKUEBNLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
