# Service YAML
apiVersion: v1 
kind: Service
metadata:
  name: tt-api
spec:
  selector:
    app: tt-api
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
status:
  loadBalancer: {}
