apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: api.tt.golf
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tt-api
                port:
                  number: 8000
