bases:
  - ../../base
namespace: production
patchesStrategicMerge:
  - patches/tt-api-image.yaml
resources:
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: the-map
    env: config.properties