bases:
  - ../../base
namespace: production
patchesStrategicMerge:
  - patches/tt-api-image.yaml
resources:
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: envvars
    behaviour: merge
    literals:
    - TEST_ROUTE=production