apiVersion: ENC[AES256_GCM,data:8PI=,iv:XD3gocMgsC8EH4tIrmA8w3qRdVsZp7V5noxyxaMNvBo=,tag:eWxf+mRW1vWQnw1deOPx5g==,type:str]
kind: ENC[AES256_GCM,data:nEHpd/Qv,iv:cp039vXYhbbszexS5q/dkZwgaymy5qsKvYIQIkXlm3A=,tag:EQAlUDq1syd1OxDQ9GcJDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mD5+zjCX4a4hZAxi,iv:ZGwsisMpO2n8nSP3uuYRF7lqtieMl9JM/9Qf0JwWee0=,tag:Z2crpM1y7Ap/4vHGOneNkg==,type:str]
    namespace: ENC[AES256_GCM,data:vmdru06fnz0fVg==,iv:XH2q4dngsCng+1rJnkBEe1PMtDlGvZ2O53eDy6r9tBw=,tag:/LxBqpd/AznuZgbN4I59zg==,type:str]
type: ENC[AES256_GCM,data:CE0dK0sd,iv:PxF4W6GefZ3cKdkB/NGPK0W43fV2/03LPvSU7x9DAGg=,tag:nS/ArIVpBDSNJOJa9jPN/A==,type:str]
data:
    pass: ENC[AES256_GCM,data:o4y8vlp2tNdnSL5uc5kEFKgs3a8=,iv:JwhzXDLMD++98L0zrVukPekX7ZlPXW3rOGqvb4+1g2I=,tag:vLGCeHwBE392YFi/A+z8ow==,type:str]
    user: ENC[AES256_GCM,data:wfwxmw==,iv:ctXdtWYRAJvGQqaTj5Q6kux3Sv1wg6xw8N18gnynuLY=,tag:VSiZ5hdYBMN3453CPP1xhg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tourtimegolf/locations/us-central1/keyRings/tt-api-dev/cryptoKeys/gke
          created_at: "2024-01-23T07:06:57Z"
          enc: CiQA6t9207mZlEKvdgy1Tik88++Y0u72MsHapGl73ceTyieIAaYSSQBbbne9Z2zbkuNalK83YgMPiHJosxnGGml6aZIlQOMRb4JrjfGaoQS6W/IMTBxtp5B0hU6lNy0nAcJueSeawcWYUU/QCy1jXtE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T07:06:57Z"
    mac: ENC[AES256_GCM,data:H5A/H02Gq2RNC7hs1HSQKkSVqVODgXp6vVdyHCTFft+EgrtQ0wAp8Z4lunmMfFgTZLzMz24Uuw04P3sP2+ASse/JAkiAcqvmyOvjaDvCbM24fW5jtmzDOlUjhOXaBQNvLy8j2EkPmngoIijV50V/QHBRR4JkG4P7hm2RZg3VW1M=,iv:xdsKcgrf7kvignrNnzdlCrCIha1a/srs9odiibmKwHE=,tag:Yz9L/9UnanWxzeAr7kZEWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
