apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: stage
spec:
  ingressClassName: nginx
  rules:
    - host: api-dev.tt.golf
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tt-api
                port:
                  number: 8000
