# Service YAML
apiVersion: v1 
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: my-service
  type: LoadBalancer
status:
  loadBalancer: {}
